service: storage-signed-uploads

plugins:
  - serverless-webpack
  - serverless-export-env
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(../../../config.json):stage, env:EUBFR_STAGE, 'dev'}
  region: ${opt:region, file(../../../config.json):region, env:EUBFR_AWS_REGION, 'eu-central-1'}
  environment:
    REGION: ${self:provider.region}
    BUCKET: eubfr-${self:provider.stage}
    # export this with serverless-export-env for other services
    SIGNED_UPLOADS_API: '${self:resources.Outputs.ServiceEndpoint.Value}'
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: '*'
    - Effect: Allow
      Action:
        - iam:ListGroupsForUser
      Resource: '*'

functions:
  docroot:
    handler: src/api/docroot.handler
    name: ${self:provider.stage}-${self:service}-docroot
    memorySize: 128
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: storage
          method: get
          cors: true
  download-objects:
    handler: src/api/download.handler
    name: ${self:provider.stage}-${self:service}-download-objects
    memorySize: 128
    events:
      - http:
          path: storage/download
          method: get
          authorizer: aws_iam
  update-objects:
    handler: src/api/update.handler
    name: ${self:provider.stage}-${self:service}-update-objects
    memorySize: 128
    events:
      - http:
          path: storage/update
          method: get
          authorizer: aws_iam
  upsert-objects:
    handler: src/api/upsert.handler
    name: ${self:provider.stage}-${self:service}-upsert-objects
    memorySize: 128
    events:
      - http:
          path: storage/signed_url
          method: get
          authorizer: aws_iam

resources:
  Outputs:
    ServiceEndpoint:
      Description: The service endpoint
      Value:
        Fn::Join:
          - ''
          - - Ref: ApiGatewayRestApi
            - '.execute-api.'
            - ${self:provider.region}
            - '.amazonaws.com/'
            - ${self:provider.stage}
      Export:
        Name: '${self:provider.stage}:${self:service}:ServiceEndpoint'
