clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch --no-tags origin master ${DRONE_COMMIT_REF}
      - git checkout -qf master;
      - if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
          git checkout -qf FETCH_HEAD;
        else
          git checkout -qf ${DRONE_COMMIT_BRANCH};
        fi

pipeline:
  install:
    image: yhuard/node:latest
    pull: true
    commands:
      - yarn install --frozen-lockfile

  test-lint:
    image: yhuard/node:latest
    group: test
    commands:
      - yarn test:lint

  test-integration:
    image: yhuard/node:latest
    group: test
    commands:
      - yarn test:integration

  test-unit:
    image: yhuard/node:latest
    group: test
    commands:
      - yarn test:unit
