clone:
  git:
    image: plugins/git
    commands:
      - git init
      - git remote add origin ${DRONE_REMOTE_URL}
      - git fetch --no-tags origin master ${DRONE_COMMIT_REF}
      - git checkout -qf master;
      - if [ "${DRONE_BUILD_EVENT}" == "pull_request" ] || [ "${DRONE_BUILD_EVENT}" == "tag" ] ; then
          git checkout -qf FETCH_HEAD;
        else
          git checkout -qf ${DRONE_COMMIT_BRANCH};
        fi

pipeline:
  install:
    image: node:8.5
    commands:
      - yarn install --frozen-lockfile

  test-lint:
    image: node:8.5
    group: test
    commands:
      - yarn test:lint

  test-flow:
    image: node:8.5
    group: test
    commands:
      - yarn test:flow

  test-integration:
    image: node:8.5
    group: test
    commands:
      - yarn test:integration

  test-unit:
    image: node:8.5
    group: test
    commands:
      - yarn test:unit

  build-documentation:
    image: node:8.5
    commands:
      - yarn docs:html
    when:
      event: [push]
      branch: feat/automate-docs-EUBFR-144

  deploy-pages:
    image: node:8.5
    secrets: [ GH_TOKEN ]
    commands:
      - ./scripts/deployment/deploy-documentation.sh
    when:
      event: [push]
      branch: feat/automate-docs-EUBFR-144
