service: ingestion-etl-budg-csv

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  eubfrEnvironment: ${env:EUBFR_ENV, 'dev'}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, file(../../../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

functions:
  parseCsv:
    handler: src/handler.parseCsv
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-etl-budg-csv"
          topicName: ${self:provider.stage}-etl-budg-csv

resources:
  Resources:
    SNSTopicBUDGCSV:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-etl-budg-csv
        DisplayName: BUDG CSV ETL
    SNSTopicBUDGCSVPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowIngestionManagerToPushNotificationEffect
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
          -
            Ref: SNSTopicBUDGCSV
