service: ingestion-etl-budg-csv

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  eubfrEnvironment: ${env:EUBFR_ENV, 'dev'}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, file(../../../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

functions:
  parseCsv:
    handler: src/handler.parseCsv
    events:
      - sns:
          topicName: ${self:provider.stage}-etl-budg-csv
          displayName: BUDG CSV ETL
