service: storage-objects

plugins:
  - serverless-s3-remover

custom:
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  remover:
     buckets:
       - eubfr-${self:provider.stage}

provider:
  name: aws
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

resources:
  Resources:
    ObjectCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-object-created
    ObjectRemovedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-object-removed
    ObjectEventsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal: '*'
              Action: sns:Publish
              Resource: '*'
              Condition:
                ArnLike:
                  aws:SourceArn:
                    Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - eubfr-${self:provider.stage}
        Topics:
        - Ref: ObjectCreatedTopic
        - Ref: ObjectRemovedTopic
    SourceBucket:
      Type: AWS::S3::Bucket
      DependsOn: ObjectEventsTopicPolicy
      Properties:
        BucketName: eubfr-${self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "Authorization"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - "*"
        NotificationConfiguration:
          TopicConfigurations:
            -
              Event: s3:ObjectCreated:*
              Topic:
                Ref: ObjectCreatedTopic
            -
              Event: s3:ObjectRemoved:*
              Topic:
                Ref: ObjectRemovedTopic
    SourceBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: SourceBucket
        PolicyDocument:
          Statement:
            -
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  -
                    - 'arn:aws:s3:::'
                    - eubfr-${self:provider.stage}
                    - '/*'
