service: enrichment-manager

plugins:
  - serverless-webpack

custom:
  esIndex: ${self:provider.stage}-projects
  webpackIncludeModules: true
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  queueName: ${self:provider.stage}-enrichment-backlog

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource: "arn:aws:sqs:${self:provider.region}:*:*"
    - Effect: "Allow"
      Action: "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:${self:provider.region}:*:${self:provider.stage}-${self:service}-onTaskCalled"
    - Effect: "Allow"
      Action: "es:*"
      Resource: "arn:aws:es:${self:provider.region}:*:domain/*"

functions:
  onFileIngested:
    handler: src/events/onFileIngested.handler
    name: ${self:provider.stage}-${self:service}-onFileIngested
    memorySize: 256
    timeout: 300
    environment:
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
      QUEUE_NAME: ${self:custom.queueName}
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-onEnrichmentRequested"
          topicName: ${self:provider.stage}-onEnrichmentRequested
  onWorkerScheduled:
    handler: src/events/onWorkerScheduled.handler
    name: ${self:provider.stage}-${self:service}-onWorkerScheduled
    memorySize: 256
    timeout: 120
    environment:
      REGION: ${self:provider.region}
      QUEUE_NAME: ${self:custom.queueName}
      lambda: ${self:provider.stage}-${self:service}-onTaskCalled
    events:
      - schedule: rate(2 minutes)
  onTaskCalled:
    handler: src/events/onTaskCalled.handler
    name: ${self:provider.stage}-${self:service}-onTaskCalled
    timeout: 30
    memorySize: 256
    environment:
      API:
        Fn::ImportValue: ${self:custom.eubfrEnvironment}:resources-elasticsearch:PublicEndpoint
      INDEX: ${self:custom.esIndex}

resources:
  Resources:
    EnrichmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-onEnrichmentRequested
    EnrichmentTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowAllToRequestEnrichment
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
        - Ref: EnrichmentTopic
    BacklogQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
        MessageRetentionPeriod: '1209600'
        VisibilityTimeout: '60'
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
            - DeadLetterQueue
            - Arn
          maxReceiveCount: '10'
    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}-dead-letter-queue
        MessageRetentionPeriod: '1209600'
