service: enrichment-manager

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

functions:
  onFileIngested:
    handler: src/events/onFileIngested.handler
    name: ${self:provider.stage}-${self:service}-onFileIngested
    memorySize: 256
    environment:
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-onEnrichmentRequested"
          topicName: ${self:provider.stage}-onEnrichmentRequested

resources:
  Resources:
    EnrichmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-onEnrichmentRequested
    EnrichmentTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowAllToRequestEnrichment
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
        - Ref: EnrichmentTopic
