service: enrichment-manager

plugins:
  - serverless-webpack

custom:
  esIndex: ${self:provider.stage}-projects
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(../../../config.json):stage, env:EUBFR_STAGE, 'dev'}
  region: ${opt:region, file(../../../config.json):region, env:EUBFR_AWS_REGION, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

functions:
  onFileIngested:
    handler: src/events/onFileIngested.handler
    name: ${self:provider.stage}-${self:service}-onFileIngested
    memorySize: 256
    timeout: 300
    environment:
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-onEnrichmentRequested"
          topicName: ${self:provider.stage}-onEnrichmentRequested

resources:
  Resources:
    EnrichmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-onEnrichmentRequested
    EnrichmentTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowAllToRequestEnrichment
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
        - Ref: EnrichmentTopic
    EnrichRecordTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-onEnrichRecordRequested
    EnrichRecordTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowAllToRequestRecordEnrichment
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
        - Ref: EnrichRecordTopic
