service: example01

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  eubfrEnvironment: ${env:EUBFR_ENV, 'dev'}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

functions:
  hello-custom:
    handler: src/handler.hello
    events: # All events associated with this function
      - http:
          path: hello/{name}
          method: get
          request:
            parameters:
              paths:
                name: true
  hello-world:
    handler: src/handler.hello
    events: # All events associated with this function
      - http:
          path: hello
          method: get
      - sns:
          topicName: ${self:provider.stage}-aggregate
          displayName: Data aggregation pipeline
