service: example01

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  # Enable auto-packing of external modules
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello-custom:
    handler: src/handler.hello
    events: # All events associated with this function
      - http:
          path: hello/{name}
          method: get
          request:
            parameters:
              paths:
                name: true
  hello-world:
    handler: src/handler.hello
    events: # All events associated with this function
      - http:
          path: hello
          method: get
