service: ingestion-store

plugins:
  - serverless-dynamodb-autoscaling

custom:
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  DYNAMODB_TABLE: ${self:provider.stage}-ingestion-store
  capacities:
    - table: IngestionStoreTable
      read:
        minimum: 5        # Minimum read capacity
        maximum: 1000     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 5        # Minimum write capacity
        maximum: 1000     # Maximum write capacity
        usage: 0.5        # Targeted usage percentage

provider:
  name: aws
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

resources:
  Resources:
    IngestionStoreTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.DYNAMODB_TABLE}
        AttributeDefinitions:
          -
            AttributeName: computed_key
            AttributeType: S
          -
            AttributeName: part_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: computed_key
            KeyType: HASH
          -
            AttributeName: part_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
