swagger: '2.0'
info:
  version: '2017-09-25T13:49:45Z'
  title: devkc-facade
host: wvbvh2iouh.execute-api.eu-central-1.amazonaws.com
basePath: /devkc
schemes:
  - https
paths:
  /projects:
    get:
      description: Get information about all existing projects under your account.
      responses:
        '200':
          description: Success
        '400':
          description: Bad request from producer.
        '403':
          description: Forbidden, you have to provide an API key.
        '502':
          description: Internal server error.
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:491621799026:function:facade-devkc-get-projects/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    put:
      description: Create on update projects.
      responses:
        '200':
          description: Success
        '400':
          description: Bad request from producer.
        '403':
          description: Forbidden, you have to provide an API key.
        '502':
          description: Internal server error.
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:491621799026:function:facade-devkc-upsert-projects/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  '/projects/{id}':
    get:
      description: Get information about a single project.
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad request from producer.
        '403':
          description: Forbidden, you have to provide an API key.
        '502':
          description: Internal server error.
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:491621799026:function:facade-devkc-get-single-project/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      description: Delete a specific project.
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad request from producer.
        '403':
          description: Forbidden, you have to provide an API key.
        '502':
          description: Internal server error.
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: >-
          arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:491621799026:function:facade-devkc-delete-single-project/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
