service: ingestion-etl-wifi4eu-xls

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  eubfrEnvironment: ${opt:eubfr_env, file(../../../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  bucketName: ${file(../../../../../resources/harmonized-storage/serverless.yml):custom.bucketName}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 60
  stage: ${opt:stage, file(../../../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - ${self:custom.bucketName}
             - "/*"

functions:
  parseXls:
    handler: src/events/onParseXLS.handler
    name: ${self:provider.stage}-${self:service}-parseXls
    memorySize: 1024
    environment:
      BUCKET: ${self:custom.bucketName}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-etl-wifi4eu-xls"
          topicName: ${self:provider.stage}-etl-wifi4eu-xls
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-etl-wifi4eu-xlsx"
          topicName: ${self:provider.stage}-etl-wifi4eu-xlsx

resources:
  Resources:
    SNSTopicWIFI4EUXLS:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-etl-wifi4eu-xls
        DisplayName: WIFI4EU XLS ETL
    SNSTopicWIFI4EUXLSX:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-etl-wifi4eu-xlsx
        DisplayName: WIFI4EU XLSX ETL
    SNSTopicWIFI4EUXLSPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowAnyoneToPublishMessageToSNSTopicWIFI4EUXLSPolicy
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
          - Ref: SNSTopicWIFI4EUXLS
          - Ref: SNSTopicWIFI4EUXLSX
