service: storage-meta-index

plugins:
  - serverless-stack-output
  - serverless-webpack

custom:
  webpackIncludeModules: true
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  output:
    file: .serverless/stack-output.json

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  environment:
    TABLE: ${self:custom.DYNAMODB_TABLE}

functions:
  onObjectCreated:
    handler: src/events/onObjectCreated.handler
    name: ${self:provider.stage}-${self:service}-onObjectCreated
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-object-created"
          topicName: ${self:provider.stage}-object-created
  onObjectRemoved:
    handler: src/events/onObjectRemoved.handler
    name: ${self:provider.stage}-${self:service}-onObjectRemoved
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-object-removed"
          topicName: ${self:provider.stage}-object-removed
  onStatusReported:
    handler: src/events/onStatusReported.handler
    name: ${self:provider.stage}-${self:service}-onStatusReported
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-MetaStatusReported"
          topicName: ${self:provider.stage}-MetaStatusReported

resources:
  Resources:
    MetaStatusReported:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-MetaStatusReported
    MetaStatusReportedTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal: '*'
              Action: sns:Publish
              Resource: '*'
        Topics:
        - Ref: MetaStatusReported
