service: storage-meta-index

plugins:
  - serverless-stack-output
  - serverless-dynamodb-autoscaling
  - serverless-webpack

custom:
  webpackIncludeModules: true
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  DYNAMODB_TABLE: ${self:provider.stage}-meta
  capacities:
    - table: MetaIndexDynamoDbTable  # DynamoDB Resource
      read:
        minimum: 5        # Minimum read capacity
        maximum: 1000     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 5        # Minimum write capacity
        maximum: 100      # Maximum write capacity
        usage: 0.5        # Targeted usage percentage
  output:
    file: .serverless/stack-output.json

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  environment:
    TABLE: ${self:custom.DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - iam:ListGroupsForUser
      Resource: "*"

functions:
  onObjectCreated:
    handler: src/events/onObjectCreated.handler
    name: ${self:provider.stage}-${self:service}-onObjectCreated
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-object-created"
          topicName: ${self:provider.stage}-object-created
  onObjectRemoved:
    handler: src/events/onObjectRemoved.handler
    name: ${self:provider.stage}-${self:service}-onObjectRemoved
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-object-removed"
          topicName: ${self:provider.stage}-object-removed
  onETLSuccess:
    handler: src/events/onETLSuccess.handler
    name: ${self:provider.stage}-${self:service}-onETLSuccess
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              -
                - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-etl-success"
          topicName: ${self:provider.stage}-etl-success
  listProjects:
    handler: src/api/list.handler
    name: ${self:provider.stage}-${self:service}-list
    environment:
      TABLE: ${self:custom.DYNAMODB_TABLE}
    events:
      - http:
          path: meta-index/list
          method: get
          authorizer: aws_iam

resources:
  Resources:
    MetaIndexDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.DYNAMODB_TABLE}
        AttributeDefinitions:
          -
            AttributeName: computed_key
            AttributeType: S
        KeySchema:
          -
            AttributeName: computed_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
