service: ingestion-etl-agri-csv

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  eubfrEnvironment: ${opt:eubfr_env, file(../../../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  bucketName: ${file(../../../../../resources/harmonized-storage/serverless.yml):custom.bucketName}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 60
  stage: ${opt:stage, file(../../../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - ${self:custom.bucketName}
             - "/*"

functions:
  parseCsv:
    handler: src/events/onParseCSV.handler
    name: ${self:provider.stage}-${self:service}-parseCsv
    memorySize: 256
    environment:
      BUCKET: ${self:custom.bucketName}
      REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:provider.stage}-etl-agri-csv"
          topicName: ${self:provider.stage}-etl-agri-csv

resources:
  Resources:
    SNSTopicBUDGCSV:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-etl-agri-csv
        DisplayName: BUDG CSV ETL
    SNSTopicBUDGCSVPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Sid: AllowIngestionManagerToPushNotificationEffect
              Action:
                - sns:Publish
              Effect: Allow
              Resource: "*"
              Principal: "*"
        Topics:
          -
            Ref: SNSTopicBUDGCSV
