service: resources-harmonized-storage

plugins:
  - serverless-s3-remover

custom:
  eubfrEnvironment: ${opt:eubfr_env, file(../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  bucketName: eubfr-${self:provider.stage}-harmonized
  remover:
    buckets:
      - ${self:custom.bucketName}

provider:
  name: aws
  stage: ${opt:stage, file(../../config.json):stage, env:EUBFR_STAGE, 'dev'}
  region: ${opt:region, file(../../config.json):region, env:EUBFR_AWS_REGION, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

resources:
  Resources:
    HarmonizedObjectCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-harmonized-object-created
    HarmonizedObjectRemovedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-harmonized-object-removed
    HarmonizedObjectEventsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: sns:Publish
              Resource: '*'
              Condition:
                ArnLike:
                  aws:SourceArn:
                    Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - ${self:custom.bucketName}
        Topics:
          - Ref: HarmonizedObjectCreatedTopic
          - Ref: HarmonizedObjectRemovedTopic
    HarmonizedSourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:*
              Topic:
                Ref: HarmonizedObjectCreatedTopic
            - Event: s3:ObjectRemoved:*
              Topic:
                Ref: HarmonizedObjectRemovedTopic
    HarmonizedSourceBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.bucketName}
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - ${self:custom.bucketName}
                    - '/*'
