service: demo-website

plugins:
  - serverless-finch
  - serverless-export-env

custom:
  client:
    bucketName: eubfr-${self:provider.stage}-demo-website
    distributionFolder: build
  eubfrEnvironment: ${opt:eubfr_env, file(../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}
  environment:
    REACT_APP_STAGE: ${self:provider.stage}
    REACT_APP_ES_PUBLIC_ENDPOINT:
      Fn::ImportValue: ${self:custom.eubfrEnvironment}:resources-elasticsearch:PublicEndpoint

resources:
  Resources:
    DeployBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.client.bucketName}
