service: ingestion-etl-results

custom:
  eubfrEnvironment: ${opt:eubfr_env, file(../../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}

provider:
  name: aws
  stage: ${opt:stage, file(../../../config.json):stage, 'dev'}
  region: ${opt:region, file(../../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

resources:
  Resources:
    ETLSuccessTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-etl-success
    ETLFailureTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:provider.stage}-etl-failure
    ETLResultsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal: '*'
              Action: sns:Publish
              Resource: '*'
        Topics:
        - Ref: ETLSuccessTopic
        - Ref: ETLFailureTopic
