service: resources-elasticsearch

plugins:
  - serverless-plugin-elasticsearch-index

custom:
  eubfrEnvironment: ${opt:eubfr_env, file(../../config.json):eubfr_env, env:EUBFR_ENV, 'dev'}
  publicDomain: ${self:custom.eubfrEnvironment}-public
  privateDomain: ${self:custom.eubfrEnvironment}-private
  slsEsIndices:
    -
      index: ${opt:stage, file(../../config.json):stage, 'dev'}-projects
      mapping: '${file(./mappings/project.js)}'
      region: ${opt:region, file(../../config.json):region, 'eu-central-1'}
      endpointName: ${self:custom.eubfrEnvironment}:resources-elasticsearch:PublicEndpoint
    -
      index: ${opt:stage, file(../../config.json):stage, 'dev'}-meta
      mapping: ${file(./mappings/meta.js)}
      region: ${opt:region, file(../../config.json):region, 'eu-central-1'}
      endpointName: ${self:custom.eubfrEnvironment}:resources-elasticsearch:PrivateEndpoint
    -
      index: ${opt:stage, file(../../config.json):stage, 'dev'}-logs
      mapping: ${file(./mappings/logs.js)}
      region: ${opt:region, file(../../config.json):region, 'eu-central-1'}
      endpointName: ${self:custom.eubfrEnvironment}:resources-elasticsearch:PrivateEndpoint

provider:
  name: aws
  # Global resource, uses eubfrEnvironment as a stage
  stage: ${self:custom.eubfrEnvironment}
  region: ${opt:region, file(../../config.json):region, 'eu-central-1'}
  deploymentBucket:
    name: eubfr-${self:custom.eubfrEnvironment}-deploy
  stackTags:
    ENV: ${self:custom.eubfrEnvironment}

resources:
  Resources:
    PublicElasticSearchDomain:
      Type: AWS::Elasticsearch::Domain
      # Don't delete the elastic search instance when the CF stack is deleted
      DeletionPolicy: Retain
      Properties:
        DomainName: ${self:custom.publicDomain}
        ElasticsearchVersion: '6.2'
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        AccessPolicies:
          Version: '2012-10-17'
          Statement:
          # Public can query for information
          - Effect: Allow
            Principal: "*"
            Action:
             - "es:ESHttpHead"
             - "es:ESHttpGet"
            Resource: "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*"
          - Effect: Allow
            Principal: "*"
            Action:
             - "es:ESHttpPost"
            Resource:
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_analyze"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_cat"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_count"
              # _field_stats and _field_caps are same https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-field-stats.html
              # though AWS supports only the deprecated _field_stats for the moment
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_field_stats"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_field_caps"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_mtermvectors"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.publicDomain}/*_search"
          # Lambda can take actions on the ES domain
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "es:*"
    PrivateElasticSearchDomain:
      Type: AWS::Elasticsearch::Domain
      # Don't delete the elastic search instance when the CF stack is deleted
      DeletionPolicy: Retain
      Properties:
        DomainName: ${self:custom.privateDomain}
        ElasticsearchVersion: '6.2'
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        AccessPolicies:
          Version: '2012-10-17'
          Statement:
          # Public can query for information
          - Effect: Allow
            Principal: "*"
            Action:
             - "es:ESHttpHead"
             - "es:ESHttpGet"
            Resource: "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*"
          - Effect: Allow
            Principal: "*"
            Action:
             - "es:ESHttpPost"
            Resource:
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_analyze"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_cat"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_count"
              # _field_stats and _field_caps are same https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-field-stats.html
              # though AWS supports only the deprecated _field_stats for the moment
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_field_stats"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_field_caps"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_mtermvectors"
              - "arn:aws:es:${self:provider.region}:*:domain/${self:custom.privateDomain}/*_search"
          # Lambda can take actions on the ES domain
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "es:*"
  Outputs:
    PublicEndpoint:
      Description: The public elasticsearch domain.
      Value:
        Fn::GetAtt: ["PublicElasticSearchDomain", "DomainEndpoint"]
      Export:
        # Global varibale, uses eubfrEnvironment instead of stage
        Name: "${self:custom.eubfrEnvironment}:${self:service}:PublicEndpoint"
    PrivateEndpoint:
      Description: The private elasticsearch domain.
      Value:
        Fn::GetAtt: ["PrivateElasticSearchDomain", "DomainEndpoint"]
      Export:
        # Global varibale, uses eubfrEnvironment instead of stage
        Name: "${self:custom.eubfrEnvironment}:${self:service}:PrivateEndpoint"
